//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFrontLab.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bike
    {
        public int BikeID { get; set; }
        public string BikeModel { get; set; }
        public Nullable<int> BikeTypeID { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public System.DateTime Year { get; set; }
        public string BikeImage { get; set; }
        public string Description { get; set; }
        public Nullable<int> TireID { get; set; }
        public Nullable<int> BikeStatusID { get; set; }
        public int BikeMakeID { get; set; }
        public Nullable<bool> IsSiteFeature { get; set; }
    
        public virtual BikeMakeID BikeMakeID1 { get; set; }
        public virtual BikeStatus BikeStatus { get; set; }
        public virtual BikeType BikeType { get; set; }
        public virtual TireType TireType { get; set; }
    }
}
