//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFrontLab.DATA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoreFrontEntities1 : DbContext
    {
        public StoreFrontEntities1()
            : base("name=StoreFrontEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BikeMakeID> BikeMakeIDs { get; set; }
        public virtual DbSet<Bike> Bikes { get; set; }
        public virtual DbSet<BikeStatus> BikeStatuses { get; set; }
        public virtual DbSet<BikeType> BikeTypes { get; set; }
        public virtual DbSet<TireType> TireTypes { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
    }
}
